echo p ArayPass | mocka
echo p Areas | mocka
echo p Arrays2 | mocka
echo p Arrays | mocka
echo p BigRec | mocka
echo p BitOps | mocka
echo p BoolMath | mocka
echo p CardMath | mocka
echo p CaseDemo | mocka
echo p CharDemo | mocka
echo p Constant | mocka
echo p DumbConv | mocka
echo p DynRec | mocka
echo p Entypes | mocka
echo p FirstEx | mocka
echo p Function | mocka
echo p Garden | mocka
echo p GoodForm | mocka
echo p IfDemo | mocka
echo p IntMath | mocka
echo p IntVar | mocka
echo p LastProg | mocka
echo p LinkList | mocka
echo p LocMod1 | mocka
echo p LocMod2 | mocka
echo p LoopDemo | mocka
echo p LoopIf | mocka
echo p ModComs | mocka
echo p MoreProg | mocka
echo p OverProg | mocka
echo p Pointers | mocka
echo p Proced1 | mocka
echo p Proced2 | mocka
echo p Proced3 | mocka
echo p Proced4 | mocka
echo p Proced5 | mocka
echo p ProcType | mocka
echo p PuppyDog | mocka
echo p Real2Mon | mocka
echo p RealMath | mocka
echo p Recursion | mocka
echo p Sets | mocka
echo p SimplIn | mocka
echo p SimplOut | mocka
echo p SmallRec | mocka
echo p StringEx | mocka
echo p Subrange | mocka
echo p TempConv | mocka
echo p Transfer | mocka
echo p TypeRel | mocka
echo p Types | mocka
echo p UglyForm | mocka
echo p VarRec | mocka
echo p WriteSm | mocka
